### ISSUE TITLE
[Failed Test] Or perhaps wrong test

### ISSUE THREAD

**Issue by maxoja** [ssantichaivekin/eMPRess#59] opened 2020-06-05 10:59 UTC
when running
`python -m unittest discover "./test"`

It gives the following error at .\test\test_empress_wrapper.py line 30
`AttributeError: 'NoneType' object has no attribute 'draw_to_file'`

**Comment by ssantichaivekin** [comment] 2020-06-05 17:43
Ah this is my bad. I'm planning to convert the file to a test but it's still just an example on how the interface is supposed to be used.

**Comment by ssantichaivekin** [comment] 2020-06-05 17:43
I will convert it to a test soon.

**Comment by ssantichaivekin** [comment] 2020-06-05 17:46
Duplicate of #32 .

**Closed by ssantichaivekin** 2020-06-05 17:46 UTC

**Comment by maxoja** [comment] 2020-06-05 19:49
Awesome, thanks!
